// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./INoirProofVerifier.sol";
import "./IInputProofVerifier.sol";

/// @notice Adapter per verifier Solidity Barretenberg/Noir. Permette di registrare ciphertext omomorfici esterni.
/// @dev Il payload della prova è codificato ABI come:
/// `(address,bytes32,bytes32,uint256,uint256,bytes32,bytes,bytes32[])`,
/// dove i primi campi sono owner, ciphertextHash, metadataHash, minValue,
/// maxValue e nonce, seguiti dai byte della prova Noir e dagli input pubblici.
contract NoirEnergyInputVerifierAdapter is IInputProofVerifier {
    bytes32 public constant VERIFIED_INPUT_TYPEHASH = keccak256("BESUFHE_VERIFIED_INPUT_V1");
    uint256 private constant LOW_128_MASK = type(uint128).max;
    uint256 private constant UINT64_MAX = type(uint64).max;
    uint256 private constant BN254_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 private constant PUBLIC_INPUT_COUNT = 6;

    address public owner;
    INoirProofVerifier public verifier;
    bool public configurationFrozen;

    error NotOwner(address caller);
    error ZeroAddress();
    error ConfigurationAlreadyFrozen();
    error ConfigurationIsFrozen();

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    event VerifierUpdated(address indexed previousVerifier, address indexed newVerifier);
    event ConfigurationFrozen(address indexed owner, address indexed verifier);

    constructor(address initialVerifier) {
        if (initialVerifier == address(0)) {
            revert ZeroAddress();
        }
        owner = msg.sender;
        verifier = INoirProofVerifier(initialVerifier);
        emit OwnershipTransferred(address(0), msg.sender);
        emit VerifierUpdated(address(0), initialVerifier);
    }

    function transferOwnership(address newOwner) external onlyOwner {
        if (newOwner == address(0)) {
            revert ZeroAddress();
        }
        emit OwnershipTransferred(owner, newOwner);
        owner = newOwner;
    }

    function setVerifier(address newVerifier) external onlyOwner {
        if (configurationFrozen) {
            revert ConfigurationIsFrozen();
        }
        if (newVerifier == address(0)) {
            revert ZeroAddress();
        }
        emit VerifierUpdated(address(verifier), newVerifier);
        verifier = INoirProofVerifier(newVerifier);
    }

    function freezeConfiguration() external onlyOwner {
        if (configurationFrozen) {
            revert ConfigurationAlreadyFrozen();
        }
        configurationFrozen = true;
        emit ConfigurationFrozen(msg.sender, address(verifier));
    }

    function verifyInputProof(bytes32 inputDigest, bytes calldata proof) external view returns (bool) {
        (
            address inputOwner,
            bytes32 ciphertextHash,
            bytes32 zkMetadataHash,
            uint256 minValue,
            uint256 maxValue,
            bytes32 nonce,
            bytes memory noirProof,
            bytes32[] memory providedPublicInputs
        ) = abi.decode(proof, (address, bytes32, bytes32, uint256, uint256, bytes32, bytes, bytes32[]));

        if (
            minValue > maxValue || maxValue > UINT64_MAX || uint256(zkMetadataHash) >= BN254_SCALAR_FIELD
                || providedPublicInputs.length != PUBLIC_INPUT_COUNT
        ) {
            return false;
        }

        bytes32 inputContextHash = keccak256(abi.encode(zkMetadataHash, minValue, maxValue));
        bytes32 expectedDigest = keccak256(
            abi.encode(
                VERIFIED_INPUT_TYPEHASH,
                block.chainid,
                msg.sender,
                inputOwner,
                ciphertextHash,
                inputContextHash,
                nonce
            )
        );
        if (expectedDigest != inputDigest) {
            return false;
        }

        bytes32[] memory expectedPublicInputs =
            publicInputs(inputOwner, ciphertextHash, zkMetadataHash, minValue, maxValue);
        for (uint256 i = 0; i < PUBLIC_INPUT_COUNT; i++) {
            if (providedPublicInputs[i] != expectedPublicInputs[i]) {
                return false;
            }
        }

        return verifier.verify(noirProof, providedPublicInputs);
    }

    /// @notice Public input order generated by the Noir circuit: ciphertextHashHi, ciphertextHashLo, owner, minValue, maxValue, metadataHash.
    function publicInputs(
        address inputOwner,
        bytes32 ciphertextHash,
        bytes32 zkMetadataHash,
        uint256 minValue,
        uint256 maxValue
    ) public pure returns (bytes32[] memory inputs) {
        uint256 ciphertextHashValue = uint256(ciphertextHash);
        inputs = new bytes32[](PUBLIC_INPUT_COUNT);
        inputs[0] = bytes32(ciphertextHashValue >> 128);
        inputs[1] = bytes32(ciphertextHashValue & LOW_128_MASK);
        inputs[2] = bytes32(uint256(uint160(inputOwner)));
        inputs[3] = bytes32(minValue);
        inputs[4] = bytes32(maxValue);
        inputs[5] = zkMetadataHash;
    }

    modifier onlyOwner() {
        if (msg.sender != owner) {
            revert NotOwner(msg.sender);
        }
        _;
    }
}
