// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./INoirProofVerifier.sol";
import "./IOperationProofVerifier.sol";

/// @notice Adapter per operation backed zk-proof relative a risultati FHE supportati.
/// @dev Il circuito Noir dimostra la conoscenza di un segreto del coprocessore il cui
/// commitment Poseidon è autorizzato, e vincola tale segreto al digest dell’operazione.
///
/// Il payload della prova è codificato ABI come:
/// `(bytes32,bytes32,bytes,bytes32[])`, cioè authorityCommitment,
/// attestationHash, byte della prova Noir e input pubblici Noir.
contract NoirOperationProofVerifierAdapter is IOperationProofVerifier {
    uint256 private constant LOW_128_MASK = type(uint128).max;
    // Definisce lo spazio scalare ammesso su cui possono essere generati i digest
    uint256 private constant BN254_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 private constant PUBLIC_INPUT_COUNT = 4;

    address public owner;
    INoirProofVerifier public verifier;
    bytes32 public authorizedAuthorityCommitment;
    bool public configurationFrozen;

    error NotOwner(address caller);
    error ZeroAddress();
    error InvalidField(bytes32 value);
    error ConfigurationAlreadyFrozen();
    error ConfigurationIsFrozen();

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    event VerifierUpdated(address indexed previousVerifier, address indexed newVerifier);
    event AuthorityCommitmentUpdated(bytes32 indexed previousCommitment, bytes32 indexed newCommitment);
    event ConfigurationFrozen(address indexed owner, address indexed verifier, bytes32 indexed authorityCommitment);

    constructor(address initialVerifier, bytes32 initialAuthorityCommitment) {
        if (initialVerifier == address(0)) {
            revert ZeroAddress();
        }
        _requireField(initialAuthorityCommitment);
        owner = msg.sender;
        verifier = INoirProofVerifier(initialVerifier);
        authorizedAuthorityCommitment = initialAuthorityCommitment;
        emit OwnershipTransferred(address(0), msg.sender);
        emit VerifierUpdated(address(0), initialVerifier);
        emit AuthorityCommitmentUpdated(bytes32(0), initialAuthorityCommitment);
    }

    function transferOwnership(address newOwner) external onlyOwner {
        if (newOwner == address(0)) {
            revert ZeroAddress();
        }
        emit OwnershipTransferred(owner, newOwner);
        owner = newOwner;
    }

    function setVerifier(address newVerifier) external onlyOwner {
        if (configurationFrozen) {
            revert ConfigurationIsFrozen();
        }
        if (newVerifier == address(0)) {
            revert ZeroAddress();
        }
        emit VerifierUpdated(address(verifier), newVerifier);
        verifier = INoirProofVerifier(newVerifier);
    }

    function setAuthorizedAuthorityCommitment(bytes32 newAuthorityCommitment) external onlyOwner {
        if (configurationFrozen) {
            revert ConfigurationIsFrozen();
        }
        _requireField(newAuthorityCommitment);
        emit AuthorityCommitmentUpdated(authorizedAuthorityCommitment, newAuthorityCommitment);
        authorizedAuthorityCommitment = newAuthorityCommitment;
    }

    function freezeConfiguration() external onlyOwner {
        if (configurationFrozen) {
            revert ConfigurationAlreadyFrozen();
        }
        configurationFrozen = true;
        emit ConfigurationFrozen(msg.sender, address(verifier), authorizedAuthorityCommitment);
    }

    function verifyOperationProof(bytes32 operationDigest, bytes calldata proof) external view returns (bool) {
        (
            bytes32 authorityCommitment,
            bytes32 attestationHash,
            bytes memory noirProof,
            bytes32[] memory providedPublicInputs
        ) = abi.decode(proof, (bytes32, bytes32, bytes, bytes32[]));

        if (
            authorityCommitment != authorizedAuthorityCommitment || uint256(attestationHash) >= BN254_SCALAR_FIELD
                || providedPublicInputs.length != PUBLIC_INPUT_COUNT
        ) {
            return false;
        }

        bytes32[] memory expectedPublicInputs =
            publicInputs(operationDigest, authorityCommitment, attestationHash);
        for (uint256 i = 0; i < PUBLIC_INPUT_COUNT; i++) {
            if (providedPublicInputs[i] != expectedPublicInputs[i]) {
                return false;
            }
        }

        return verifier.verify(noirProof, providedPublicInputs);
    }

    /// @notice Public input order generated by the Noir circuit: operationDigestHi, operationDigestLo, authorityCommitment, attestationHash.
    function publicInputs(bytes32 operationDigest, bytes32 authorityCommitment, bytes32 attestationHash)
        public
        pure
        returns (bytes32[] memory inputs)
    {
        uint256 digestValue = uint256(operationDigest);
        inputs = new bytes32[](PUBLIC_INPUT_COUNT);
        inputs[0] = bytes32(digestValue >> 128);
        inputs[1] = bytes32(digestValue & LOW_128_MASK);
        inputs[2] = authorityCommitment;
        inputs[3] = attestationHash;
    }

    function _requireField(bytes32 value) private pure {
        if (uint256(value) >= BN254_SCALAR_FIELD) {
            revert InvalidField(value);
        }
    }

    modifier onlyOwner() {
        if (msg.sender != owner) {
            revert NotOwner(msg.sender);
        }
        _;
    }
}
